# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([32,55,76,12,99])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(array))

[12 32 55 76 99]


# Problem 2

In [3]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayi = np.array([10,15,30,45,60])
print(sayi)
print("*"*15)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
arasayi = np.arange(5,15)
print(arasayi)
print("*"*15)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
beserbeser = np.arange(50,100,5)
print(beserbeser)
print("*"*15)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilarsifir= np.zeros(10)
print(sayilarsifir)
print("*"*15)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar1 =np.ones(10)
print(sayilar1)
print("*"*15)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
aralikli = np.linspace(0,100,5)
print(aralikli)
print("*"*15)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
rasgele = np.random.randint(10,31, size= 5)
print(rasgele)
print("*"*15)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
eksi = np.random.uniform(-1,1, size=10)
print(eksi)
print("*"*15)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix = np.random.randint(10,50,size=(3,5))
print(matrix)
print("*"*15)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
matrix = np.random.randint(10,50,size=(3,5))
print(matrix)
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))
print("*"*15)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[29 13 21 11 26]
[ 0.17795158 -0.60817815  0.0253929   0.83578213  0.8403352  -0.48564079
  0.10234833 -0.43932499 -0.17390665 -0.60306216]
[[35 12 24 18 22]
 [23 16 32 31 37]
 [11 15 37 32 13]]
***************
[[13 18 44 32 20]
 [19 30 27 20 17]
 [30 46 22 10 40]]
[62 94 93 62 77]
[127 113 148]
***************


In [4]:
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
matrix = np.random.randint(10,50,size=(3,5))
print(matrix)
print(matrix.max())
print(matrix.min())
print(matrix.mean())
print("*"*15)
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
matrix = np.random.randint(10,50,size=(3,5))
print(matrix)
print(matrix.argmax())
print("*"*15)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
aralik = np.random.randint(10,20, size=8)
print(aralik[:3])
print("*"*15)
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(aralik[::-1])
print("*"*15)
# 15- Üretilen matrisin ilk satırını seçiniz.
print(matrix[0])
print("*"*15)
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matrix[1,2])
print("*"*15)
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matrix[:,0])
print("*"*15)
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matrix**2)
print("*"*15)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrix2 = np.random.randint(-50,50,size=(3,5))
print((matrix2 >0) & (matrix2 % 2 ==0))

[[23 24 44 47 33]
 [22 18 41 21 35]
 [31 16 14 15 36]]
47
14
28.0
***************
[[41 19 27 43 31]
 [22 29 29 37 15]
 [18 33 39 41 15]]
3
***************
[18 17 18]
***************
[18 11 12 18 16 18 17 18]
***************
[41 19 27 43 31]
***************
29
***************
[41 22 18]
[[1681  361  729 1849  961]
 [ 484  841  841 1369  225]
 [ 324 1089 1521 1681  225]]
[[False False False False  True]
 [False  True  True  True False]
 [False  True  True False False]]
