# Problem 1

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
Karisik = np.random.randint(0,10,5)
print(Karisik)
# 3 - matris'in boyutunu öğrenin
x = np.array([1,2,3,4])
print(x.shape)
# 4 - matris'i yeniden boyutlandırın
print(x.reshape(2,2))
# 5 - matris'in boyut sayısını öğrenin
print(x.ndim)


[2 9 2 1 7]
(4,)
[[1 2]
 [3 4]]
1


# Problem 2

In [10]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
teksayi= np.arange(1,11,2)
print(teksayi)
# 2 - Oluşturduğunuz matrisi parçalayın
a,b = np.split(teksayi,[2])
print(a,"*",b)
# 3 - Parçalanmış matrisleri birleştirin
birlesme = np.concatenate([a,b])
print(birlesme)

[1 3 5 7 9]
[1 3] * [5 7 9]
[1 3 5 7 9]


# Problem 3

In [20]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
rastgale = np.arange(5,101,2)

np.random.shuffle(rastgale)

sayi= rastgale[:10].reshape(5, 2)
print(sayi)
# 2 - matris'in özelliklerini inceleyin
print(sayi.ndim) # Boyut sayisi
print(sayi.shape) # Boyut bilgisi
print(sayi.size) # Toplam eleman sayisi
print(sayi.dtype) # Veri tipi


[[27 41]
 [77 13]
 [69 39]
 [67 99]
 [17 91]]
2
(5, 2)
10
int32
