# Numpy

- Numpy sayısal işlemleri hılı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayara kurmak için 'pip insall numpy' komutu ile kurulur
- Bilimsel hesaplamalar için kullanılır
- Arraylar / çok boyutlu arrayler ve matrisler üzerinde yüksek performans işlemleri yapılabilir
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçirildi
- Listelere benzerdir. Fakat verimli saklama ve vektör işlemleri için Numpy kullanılır

# Neden Numpy

In [3]:
# Klasik Yöntem
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0,len(a)):
    ab.append(a[i]* b[i])
print(ab)

[2, 6, 12, 20]


In [1]:
# Numpy ile
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)



[ 2  6 12 20]


.reshape() fonksiyonu ile arrayleri boyutlarını değiştirebiliriz.

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape() ile arraylerın boyutlarını öğrenebiliriz.

In [8]:
print(multi.shape)

(3, 3)


In [9]:
print(x.shape)

(9,)


.ndim() ile arraylerin boyut sayısı.

In [11]:
print(x.ndim)

1


In [12]:
print(multi.ndim)

2
