# Birleştirme

- .concatenate() fonksiyonu ile birleştirme yapabiliriz

In [2]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,z,y]))

[ 1  2  3  4  5 11 12 13 14 15  6  7  8  9 10]


In [6]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis = 0 ise satır bazında birleştirme
axis = 1 ise sütun nazında birleştirme

In [7]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


# Array Ayirma (Splitting)

In [11]:
import numpy as np
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [13]:
a,b,c = np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


- vsplit() fonksyionu ile array yatay olarak ayiriyor

In [11]:
n= np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

- hsplit() fonksiyonu ile array dikey olarak ayirma yapabiliriz

In [12]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

np.arange()

- Belirili bir aralıkta sayıları oluşturmak için kullanılır
- np.arange(start,stop,step)

In [14]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

np.zeros()
- 0"lardan oluşan bir numpy dizisi oluşturulması için kullanılır

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

np.ones()
- 1'lerden oluşan bir numpt dizisi oluşturulması için kullanılır

In [16]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

np.linspace()
- Belli bir aralıkta sayıları oluşturmak için kullanılır
- no.linspace(başlangıçta, bitiş, bölünecek aralık)

In [17]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [18]:
np.random.randint(0,10,3)

array([2, 1, 6])

In [19]:
np.random.randint(2,22,5)

array([14, 19,  7, 14,  2])

In [20]:
npArray = np.arange(50)
npMulti = npArray.reshape(5,10)
print(npMulti.sum(axis =1))

[ 45 145 245 345 445]


## Numpy Array'in Özellikleri

- ndim : Boyut sayısı
- shape :Boyut bilgisi
- size : Toplam Eleman sayısı
- dytpe : Veri tipi

In [22]:
a = np.random.randint(10,size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


## Array Sirlamasi(Sorting)

- Array sırlama işlemleri yapmak için numpy kütüphaneinde yer alan sort() fonksiyonu kullanılır.

In [24]:
v = np.array([8,24,232,12,42,5,55])
print(v)
v.sort()
print(v)

[  8  24 232  12  42   5  55]
[  5   8  12  24  42  55 232]


In [30]:
n = np.random.normal(20,5,(3,3))
print(n)

[[34.01914931 17.36827781 12.59315523]
 [20.38275491 18.45898983 13.4760258 ]
 [21.41849447 23.89559289 10.79064742]]


In [32]:
print(np.sort(n, axis=0))

[[20.38275491 17.36827781 10.79064742]
 [21.41849447 18.45898983 12.59315523]
 [34.01914931 23.89559289 13.4760258 ]]


In [34]:
print(np.sort(n, axis= 1))

[[12.59315523 17.36827781 34.01914931]
 [13.4760258  18.45898983 20.38275491]
 [10.79064742 21.41849447 23.89559289]]


## Indek ile Elemanlara Erişmek
- Aynı listelerde oldupu gibi index ile elemanlara eişebiliriz

In [37]:
a = np.random.randint(10,size=10)
print(a[0])

9


In [38]:
print(a[-1])

5


In [39]:
a[0] = 100
print(a)

[100   8   5   4   7   3   8   9   9   5]


In [41]:
x = np.random.randint(10,size=(3,5))
print(x)

[[8 3 9 3 6]
 [6 4 7 7 6]
 [0 5 4 2 9]]


In [42]:
print(x[0,0])

8


In [43]:
print(x[1,1])

4


In [44]:
x[1,4]= 100
print(x)

[[  8   3   9   3   6]
 [  6   4   7   7 100]
 [  0   5   4   2   9]]


In [45]:
x[1,4] = 3.14
print(x)

[[8 3 9 3 6]
 [6 4 7 7 3]
 [0 5 4 2 9]]
