In [1]:
import numpy as np 

# Slicing ile Elemanlara Erişmek ( Array Alt Kümesine Erişmek)

In [2]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [4]:
print(a[0:3])

[20 21 22]


In [5]:
print(a[:3])

[20 21 22]


In [6]:
print(a[3:])

[23 24 25 26 27 28 29]


In [7]:
print(a[1::2])

[21 23 25 27 29]


In [9]:
print(a[0::2])

[20 22 24 26 28]


In [10]:
print(a[2::2])

[22 24 26 28]


In [11]:
print(a[1::5])

[21 26]


In [12]:
b =np.random.randint(10,size=[5,5])

In [13]:
print(b)

[[0 5 1 9 4]
 [9 0 9 6 1]
 [6 6 1 0 3]
 [0 3 7 9 7]
 [0 1 1 4 1]]


In [15]:
print(b[:,0])

[0 9 6 0 0]


In [17]:
print(b[:,1])

[5 0 6 3 1]


In [18]:
print(b[0,:])

[0 5 1 9 4]


In [19]:
print(b[1,:])

[9 0 9 6 1]


In [21]:
print(b[0:2,0:3])

[[0 5 1]
 [9 0 9]]


In [22]:
print(b[::2,::2])

[[0 1 4]
 [6 1 3]
 [0 1 1]]


# Alt Küme Üzerinde İşlem Yapmak

In [23]:
alt_b =b[0:3,0:2]
alt_b

array([[0, 5],
       [9, 0],
       [6, 6]])

In [24]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b

array([[100,   5],
       [  9, 200],
       [  6,   6]])

In [25]:
print(b)

[[100   5   1   9   4]
 [  9 200   9   6   1]
 [  6   6   1   0   3]
 [  0   3   7   9   7]
 [  0   1   1   4   1]]


# Fancy Index

- Bir liste içerisinde arrayden istediğimiz indeskleir koyarak o indislerdeki verileri alabiliriz

In [26]:
v = np.arange(0,30,3)
print(v) 

[ 0  3  6  9 12 15 18 21 24 27]


In [27]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [29]:
m = np.arange(9).reshape(3,3)
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir,sutun])

[1 5]


# Koşul Ekleme İşlemleri

In [30]:
v = np.array([1,2,3,4,5])
print(v > 3)

[False False False  True  True]


In [31]:
print(v[v> 3])

[4 5]


In [32]:
print(v[v < 3])

[1 2]


In [33]:
print(v[v >= 3])

[3 4 5]


In [34]:
print(v[v <= 3])

[1 2 3]


In [35]:
print(v[v != 3])

[1 2 4 5]


In [36]:
print(v[v == 3])

[3]


# Matematiksel İşlemler

In [38]:
v = np.array([1,2,3,4,5])

print(v* 2)

[ 2  4  6  8 10]


In [39]:
print( v + 2)

[3 4 5 6 7]


In [40]:
print(v * 5 / 10)

[0.5 1.  1.5 2.  2.5]


In [41]:
print( v **2)

[ 1  4  9 16 25]


In [43]:
print(np.subtract(v,3)) #Her biriniden 3 çıkarır

[-2 -1  0  1  2]


In [45]:
print(np.add(v,2)) # Toplama

[3 4 5 6 7]


In [50]:
np.multiply(v,2) # Çarpma

array([ 2,  4,  6,  8, 10])

In [47]:
np.divide(v,2) # Bölme

array([0.5, 1. , 1.5, 2. , 2.5])

In [51]:
np.power(v,2) # Üs alma

array([ 1,  4,  9, 16, 25], dtype=int32)

In [53]:
np.mod(v , 5) #Mod alma

array([1, 2, 3, 4, 0], dtype=int32)

In [55]:
print(np.absolute(v)) #Mutlak Değer

[1 2 3 4 5]


In [57]:
print(np.sin(360))

0.9589157234143065


In [58]:
np.log(10)

2.302585092994046

In [ ]:
?np

# İki  Bilinmeyene denklem çözme

In [65]:
# 5*x0 + x1 = 12
# x0 + 3+x1 = 10
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b) # np.linalg denklem çözme
print(x)

[1.85714286 2.71428571]
